### ISSUE TITLE
Amazing work tritao

### ISSUE THREAD

**Issue by waylaidwanderer** [tritao/SteamBot#1]
Hey, just commenting to let you know how awesome this is. I've been trying to get SteamBot to work with crafting for a really long time.

Would you mind sharing how you figured out how to implement crafting?

Perhaps you can add me on Steam (http://steamcommunity.com/id/waylaidwanderer/) and we can discuss it :)

**Comment by tritao** [comment]
Thanks!

Well, I pretty much reverse engineered it by dumping the packets, looking at the raw data and making some (intelligent) guesses :)

Will you be using it for any project?

Also remember this project is not related at all to Jessecar's SteamBot.

I implemented the entire Steam trading protocol, even before it was added to SteamKit.

**Comment by ghost** [comment]
Actually, I may have implemented it into SteamBot and got it fully
functional. but thats a definite maybe

**Comment by waylaidwanderer** [comment]
Lol "maybe" - you know we already got it working

14942744 notifications@github.com wrote:

Actually, I may have implemented it into SteamBot and got it fully
functional. but thats a definite maybe

On Mon, Mar 18, 2013 at 8:05 PM, João Matos notifications@github.comwrote:

> Thanks!
> 
> Well, I pretty much reverse engineered it by dumping the packets, looking
> at the raw data and making some (intelligent) guesses :)
> 
> Will you be using it for any project?
> 
> Also remember this project is not related at all to Jessecar's SteamBot.
> 
> I implemented the entire Steam trading protocol, even before it was added
> to SteamKit.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tritao/SteamBot/issues/1#issuecomment-15090092
> .

---

**Comment by ghost** [comment]
I know we did. Ive used it. :P Its fantastic.  Im working on incorporating
it into a custom of MIST

**Comment by awillinger** [comment]
I may have found a bug... everytime I craft something, it produces untradeable metal.
For example, I traded 3 CRAFTABLE Scraps to the Bot, did AutoCraft and it produces a untradeable Reclaimed.

Anyone knows why?

**Comment by waylaidwanderer** [comment]
I don't think that's possible...

awillinger notifications@github.com wrote:

I may have found a bug... everytime I craft something, it produces untradeable metal.
For example, I traded 3 CRAFTABLE Scraps to the Bot, did AutoCraft and it produces a untradeable Reclaimed.

Anyone knows why?

---

**Comment by awillinger** [comment]
I personally don't know myself how this is possible, I am running the Version hosted here without any modifcations (on the Crafting Side).
However, there's a Glitch some Time ago, maybe that's it.

**Comment by tritao** [comment]
I have no idea, I have never seen that problem happen before.

**Comment by awillinger** [comment]
Could this be because I am crafting in a F2P Account? (I trade it to it and then Craft it there)

**Comment by tritao** [comment]
I suppose it is possible. Could you try to do the crafting manually to see if you can replicate the problem?

**Comment by waylaidwanderer** [comment]
Btw tritao, did you add me yet? I'll probably be getting on a computer in about half an hour and there's some stuff I'd like to pick your brains on in understanding Nethook and stuff

João Matos notifications@github.com wrote:

I suppose it is possible. Could you try to do the crafting manually to see if you can replicate the problem?

---

**Comment by tritao** [comment]
I did, feel free to PM me.

**Comment by awillinger** [comment]
Ok, it's not a bug with the Program... I did a craft manually, and it produced untradeable Metal again.
Gonna have to upgrade to a Premium Account then.

Thanks for your Help & doing this in General :)
